import { Product } from '@/types'

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Chaqueta Rockstar',
    price: 89.99,
    description: 'Chaqueta de cuero estilo GTA. Edición limitada con logo bordado.',
    image_url: '',
    position_3d: { x: -5, y: 0.55, z: -8 },
    stock: 10,
    category: 'ropa',
    active: true,
  },
  {
    id: 'prod-2',
    name: 'Zapatos Grove St.',
    price: 59.99,
    description: 'Sneakers exclusivos del barrio más icónico de San Andreas.',
    image_url: '',
    position_3d: { x: 5, y: 0.55, z: -8 },
    stock: 5,
    category: 'calzado',
    active: true,
  },
  {
    id: 'prod-3',
    name: 'Gorra Los Santos',
    price: 29.99,
    description: 'Gorra snapback con el escudo oficial de Los Santos.',
    image_url: '',
    position_3d: { x: -5, y: 0.55, z: 0 },
    stock: 20,
    category: 'accesorios',
    active: true,
  },
  {
    id: 'prod-4',
    name: 'Reloj Maze Bank',
    price: 149.99,
    description: 'Reloj de lujo con el logo de Maze Bank. Resistente al agua.',
    image_url: '',
    position_3d: { x: 5, y: 0.55, z: 0 },
    stock: 3,
    category: 'accesorios',
    active: true,
  },
  {
    id: 'prod-5',
    name: 'Cadena Vinewood',
    price: 199.99,
    description: 'Cadena de oro con dije de la estrella de Vinewood. Edición VIP.',
    image_url: '',
    position_3d: { x: 0, y: 1.65, z: -6 },
    stock: 2,
    category: 'joyeria',
    active: true,
  },
]
